name: AWS Threat Composer deployment

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
      
jobs:
  setup-and-deploy:
    runs-on: ubuntu-latest

    env:

      AWS_REGION: eu-west-2
      TF_VAR_aws_region: "eu-west-2"
      TF_VAR_ecr_repo_name: "achraf/threatcomposer"
      TF_VAR_acm_certificate_arn: ${{ secrets.ACM_CERTIFICATE_ARN }}
      TF_VAR_route53_zone_id: ${{ secrets.AWS_ZONE_ID }}
      TF_VAR_domain_name: "achrafm.com"
      TF_VAR_cluster_name: "tC-cluster"
      TF_VAR_app_name: "threat-composer"
      TF_VAR_subdomain: "threatcomposer"
      TF_VAR_vpc_cidr: "10.0.0.0/16"
      
      

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: 1.3.0

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Building Docker image
        run: |
          docker build -t ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.${{ env.AWS_REGION }}.amazonaws.com/achraf/threatcomposer:${{ github.sha }} .

      - name: Logging into Amazon ECR
        run: |
          aws ecr get-login-password --region ${{ env.AWS_REGION }} | docker login --username AWS --password-stdin ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.${{ env.AWS_REGION }}.amazonaws.com

      - name: Pushing Docker image to ECR
        run: |
          docker push ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.${{ env.AWS_REGION }}.amazonaws.com/achraf/threatcomposer:${{ github.sha }}

      - name: Terraform Init
        run: terraform init -upgrade
        working-directory: ./terraform

      - name: Terraform Plan
        run: terraform plan
        working-directory: ./terraform 

      - name: Terraform Apply
        run: terraform apply -auto-approve
        working-directory: ./terraform
