name: CI/CD Pipeline 

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
      
jobs:
  setup-and-deploy:
    runs-on: ubuntu-latest

    env:

      AWS_REGION: eu-west-2
      TF_VAR_execution_role_arn: "arn:aws:iam::971422696890:role/CICD-tm-role"
      TF_VAR_aws_region: "eu-west-2"
      TF_VAR_acm_certificate_arn: ${{ secrets.ACM_CERTIFICATE_ARN }}
      TF_VAR_route53_zone_id: ${{ secrets.AWS_ZONE_ID }}
      TF_VAR_ecr_image: "971422696890.dkr.ecr.eu-west-2.amazonaws.com/achraf/threatcomposer:fe3c8152d8f5de18611af5b41ada4d924b2093ea"
      TF_VAR_domain_name: "achrafm.com"
      TF_VAR_cluster_name: "tC-cluster"
      TF_VAR_app_name: "threat-composer"
      TF_VAR_subdomain: "threatcomposer"
      TF_VAR_vpc_cidr: "10.0.0.0/16"
      
      
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: 1.3.0

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Terraform Init
        run: terraform init -upgrade
        working-directory: ./terraform

      - name: Terraform Plan
        run: terraform plan
        working-directory: ./terraform 

      - name: Terraform Apply
        run: terraform apply -auto-approve
        working-directory: ./terraform

